defaults: &defaults
  working_directory: ~/openfisca-bacASable
  docker:
    - image: python:2.7.12

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip wheel
      - run:
          name: Install dependencies
          command: pip install . --upgrade && pip install ".[test]"
      - run:
          name: Run tests
          command: openfisca-run-test `circleci tests glob "tests/**/*.{yml,yaml}"` --extensions openfisca_bacASable

workflows:
  version: 2
  test:
    jobs:
      - test
