python2: &python2
  working_directory: ~/openfisca-france-local
  docker:
    - image: python:2.7.12

python3: &python3
  working_directory: ~/openfisca-france-local
  docker:
    - image: python:3.6.7

upgrade_pip: &upgrade_pip
  run:
    name: Upgrade pip
    command: pip install --upgrade pip wheel

install_dependencies: &install_dependencies
  run:
    name: Install dependencies
    command: pip install . --upgrade && pip install ".[test]"

version: 2
jobs:
  test_python2:
    <<: *python2
    steps:
      - checkout
      - *upgrade_pip
      - *install_dependencies
      - run:
          name: Run tests
          command: openfisca-run-test `circleci tests glob "tests/**/*.{yml,yaml}"` --extensions openfisca_france_local
  test_python3:
    <<: *python3
    steps:
      - checkout
      - *upgrade_pip
      - *install_dependencies
      - run:
          name: Run tests
          command: openfisca-run-test `circleci tests glob "tests/**/*.{yml,yaml}"` --extensions openfisca_france_local

workflows:
  version: 2
  test:
    jobs:
      - test_python2
      - test_python3
